ONSdigital/dp-permissions-api

- service/initialise_test.go
- service/interfaces.go
-Improvements to the initialise tests
-Interface description
Confirm that they align with the suggestions in this code review: https://github.com/ONSdigital/dp-permissions-api/pull/6
Anyone
> Improve initialise tests and interface description

- LICENSE.md
- README.md
- swagger.yaml
Created the swagger specification for the following endpoints:
- GET /roles
- GET /roles{id}
- POST /authorise
- POST /policies
- GET /policies
- DELETE /policies{id}
- GET /policies{id}
- PUT /policies{id}
Check that the endpoints and models defined in the swagger specification align with the outcomes of the permissions api workshop. I can share this with who is reviewing this pull request. 
Anyone other than myself
> Create swagger specification and update licenses and copyright to 2021

- config/config.go
- config/config_test.go
- import-roles/import-roles.go
So that the collection is more descriptive its name has been changed. So changes have been made to the config and utility to load load roles to mongo
Check the collections name has been updated to roles
Anyone
> Update collection name

- import-roles/import-roles.go
- So it is more usable update the role id to be the role name in lowercase
- Check the id is now the name from the role.json file
Anyone
> Update id to the name

- config/config.go
- go.mod
- go.sum
- mongo/mongo.go
- service/initialise.go
Connections made will now use the v2 of dp-mongodb which uses the official mongodb driver.
Config updated
Query updated
###How to review
Review code to make sure we are setting mongo configs while creating DB connections
Check tests passing
###Who can review
AnyOne
> Fix DB connection issues and upgrade dp-mongodb lib to latest

- Makefile
- ci/component.yml
- ci/scripts/component.sh
- features/roles.feature
- features/roles_id.feature
- features/steps/permissions_component.go
- features/steps/steps.go
- go.mod
- main_test.go
Add component tests - https://trello.com/c/yUiMR0YE/660-660-add-component-tests-to-permissions-api
Pull branch and run `make test-component` to confirm that all tests pass
Anyone
> add component tests for get roles api

- swagger.yaml
Update the swagger specification for the post /policies endpoint
Check that the /policies endpoint and models used in that api defined in the swagger specification align with the outcomes of the permissions /policies Post api requirement.
Anyone
> Update /policy swagger api

- api/api.go
- api/interfaces.go
- api/mock/permissionsStore.go
- api/policies.go
- api/policies_test.go
- models/policies.go
- models/policies_test.go
- mongo/mongo.go
- swagger.yaml
Add policies endpoint to add new policies to data store. Refer ticket for details: https://trello.com/c/zmzPfueI/658-658-create-new-policy-endpoint
- Make sure code changes make sense
- Make sure unit tests succeed
Anyone.
> Add /polices post end point to add new policies to data store

- api/policies_test.go
- features/post_policies.feature
- models/policies.go
- models/policies_test.go
Add component tests for post policies endpoint
Pull branch and run `make test-component` to confirm that all tests pass
Anyone
> add component tests for post policies end point

- README.md
- config/config.go
- config/config_test.go
- models/policies.go
- mongo/mongo.go
Rename MONGODB_PERMISSIONS_COLLECTION env to MONGODB_ROLES_COLLECTION.
Add a new environment variable MONGODB_POLICIES_COLLECTION.
Save policies in policies collection
Validate policies created using policies endpoint are getting saved into policies collection.
Anyone
> store policies in policies endpoint

- api/policies.go
- models/policies.go
Save policies ID to db while creating a new policy
Validate policies id is getting saved to DB
Anyone.
> save policies id in db

- go.mod
- go.sum
Service requires latest version of `dp-authorisation/v2` library.
Ensure dependency version @ `v2.3.0`
Anyone but me.
> Update version of dp-authorisation/v2 to v2.3.0

- api/api.go
- api/api_test.go
- api/interfaces.go
- api/mock/bundler.go
- api/mock/permissionsStore.go
- api/policies.go
- api/policies_test.go
- apierrors/errors.go
- features/delete_policies.feature
- mongo/mongo.go
- permissions/mock/store.go
- service/mock/healthCheck.go
- service/mock/server.go
- service/mock/store.go
- swagger.yaml
Add a delete policy endpoint.
Run tests and review code.
Anyone
> add delete policy endpoint

- go.mod
- go.sum
As per titlle.
Ensure auth version is @ `v2.11.0`
not me
> Update auth version.

- models/errors.go
- models/responses.go
Document exported identifiers
Check exports are documented.
Anyone
> Document exported identifiers

- models/responses.go
Fix typos in documentation.
Check documentation matches exported identifiers.
Anyone
> Fix typos in exported identifiers documentation

- import-script/policies.json
- import-script/roles.json
- added permissions for interactives (CRUD)
- added appropriate permissions to roles
- created a "service user" - a service that will invoke the api (only update)
> add interactives permission

- import-script/roles.json
Adding permission for administrator and collection-author to create static files
check JSON config
Anyone
> Adding permission for administrator and collection-author to create static files

- Dockerfile-local
- README.md
Local Dockerfile added to allow service to be run locally in docker.
Check docker config makes sense.
Anyone.
> add Dockerfile to allow service to be run locally in docker

- features/steps/permissions_component.go
- go.mod
- go.sum
- service/initialise.go
- service/service.go
- service/service_test.go
As per title. Update `dp-authorisation` dependency to `v2.17.0`. Add health check to report on `jwt rsa signing keys` request status.
Ensure tests pass and code looks sane.
!me
> Update the middleware constructor call and add new health check.

- import-script/roles.json
add groups:update to adminstrator role
ensure the code looks ok and the tests pass
!me
> add groups:update to adminstrator role

- api/policies_test.go
- features/delete_policies.feature
- features/get_permissions_bundle.feature
- features/get_policies.feature
- features/post_policies.feature
- import-script/policies.json
- models/policies.go
- models/policies_test.go
- permissions/bundler_test.go
- swagger.yaml
Refactored `attributes` to `attribute` and changed type from an array to a string.
Ensure all relevant changes in the codebase are made including unit tests.
Describe who worked on the changes, so that other people can review.
> refactor: unpluralised attributes and changed type to string

- .gitignore
- api/policies_test.go
- features/delete_policies.feature
- features/get_permissions_bundle.feature
- features/get_policies.feature
- features/post_policies.feature
- import-script/policies.json
- main_test.go
- models/bundle.go
- models/policies.go
- models/policies_test.go
- permissions/bundler_test.go
Change Attribute in permissions policy to  string instead of array
Check the code changes
Anyone
> Change permission policy array attributes to string attribute

- service/initialise.go
use JWT keys from env vars when creating middleware
run
Describe who worked on the changes, so that other people can review.
> use JWT keys from env vars when creating middleware

- service/initialise.go
- service/service.go
- service/service_test.go
See title
- Check changes make sense
- Run `for x in {1..20}; do go test -race -cover ./service/...; go clean -testcache; done` to make sure unit tests pass for service package.
Anyone
> Check if authorisation middleware has been instantiated before closing the middleware

- sdk/api_client.go
- sdk/api_client_test.go
Describe what you have changed and why.
Describe the steps required to test the changes.
Describe who worked on the changes, so that other people can review.
> wip(1086):added implementations for missing endpoints

- sdk/api_client.go
Add implementations for missing endpoints for API Client in SDK.
Describe the steps required to test the changes.
Describe who worked on the changes, so that other people can review.
> feat(1086):added implementations for missing endpoints

- import-script/roles.json
Add permissions for cantabular-metadata-extractor
add it the collection-creator/preview/admin for now
> add cantabular perms

- ci/build.yml
> also fix build... :sigh:

- dp-permissions-api.nomad
- go.mod
As per title.
Also, fix audit failures.
No ONS libs have been updated.
Ensure changes are similar to whats in babbage for 'spread'.
Anyone.
> Ensure deployments spread over availability zones

- Dockerfile-local
These are the changes in this release:
- Add /service to Dockerfile as safe directory for git - https://github.com/ONSdigital/dp-permissions-api/pull/118 - @cookel2
Check only expected commits present and tests pass
Anyone but me
> Release 0.26.0

- Dockerfile.concourse
- import-script/roles.json
Release branch containing…
- [Adding permissions for bundle-api](https://github.com/ONSdigital/dp-permissions-api/commit/4eedd9ee58305065aadc4dfe9f0629f8d941fe1a) @franmoore05 
- [allow bundles:delete for admin and collection author](https://github.com/ONSdigital/dp-permissions-api/commit/5369261b0ec9ca50155caface915b49d87e36ba1) @aryan-p03 
- [upgrade to ubuntu22.4 for base docker image](https://github.com/ONSdigital/dp-permissions-api/commit/f6778bfc6a22a606df635e64f7edc83665c3875c) @jessjenkins 
Ensure only expected commits and tests pass.
Anyone
> Release 1.1.0

- Dockerfile-local
- ci/build.yml
- ci/component.yml
- ci/lint.yml
- ci/unit.yml
- Upgraded golang to 1.24.6-bookworm - [Ticket](https://officefornationalstatistics.atlassian.net/browse/DIS-3677)
Check looks ok, tests pass.
!Me
> Upgrade golang to 1.24.6-bookworm

- import-script/policies.json
- import-script/roles.json
Added permissions for dis-bundle-scheduler.
Ensure the change makes sense.
Anyone.
> Adding dis-bundle-scheduler permissions
